version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: llm_automl_project/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: llm_automl_project/frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: automl_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
